### GET request to example server
#GET https://examples.http-client.intellij.net/get
#    ?generated-in=IntelliJ IDEA
#GET http://localhost:8080/create

GET http://localhost:8080/tasks/test


#### POST
POST http://localhost:8080/tasks/update
Content-Type: application/json

{
  "id" : "1",
  "contents" : "hello spring",
  "isDone" : "true"
}

#### POST
#POST http://localhost:8080/tasks/create
#Content-Type: application/json
#
#{
#"contents" : "hello summer"
#}
#
#### POST
#POST http://localhost:8080/tasks/create
#Content-Type: application/json
#
#{
#"contents" : "hello autum"
#}

### POST
POST http://localhost:8080/tasks/create
Content-Type: application/json

{
  "contents" : "hello spring"
}